apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-hour-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical-hour-management
  template:
    metadata:
      labels:
        app: medical-hour-management
    spec:
      containers:
        - name: medical-hour-management
          image: sebagq/medical-hour-management:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15